# Generated by Django 4.2.6 on 2024-01-01 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatbotmodel',
            name='updated_at',
            field=models.DateTimeField(null=True),
        ),
    ]
