# Generated by Django 4.2.6 on 2024-01-01 06:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_eventmodel_is_completed'),
        ('chatbot', '0002_alter_chatbotmodel_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatbotmodel',
            name='event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='home.eventmodel'),
        ),
    ]
