# Generated by Django 4.2.6 on 2024-01-03 06:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_eventmodel_is_completed'),
        ('chatbot', '0004_remove_chatbotmodel_event_chatbotitemmodel_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatbotitemmodel',
            name='event',
        ),
        migrations.AddField(
            model_name='chatbotitemmodel',
            name='event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='home.eventmodel'),
        ),
    ]
