# Generated by Django 4.2.6 on 2024-01-03 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0005_remove_chatbotitemmodel_event_chatbotitemmodel_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatbotitemmodel',
            name='question',
            field=models.CharField(max_length=2000, null=True),
        ),
    ]
