# Generated by Django 4.2.6 on 2024-01-03 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0006_alter_chatbotitemmodel_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatbotitemmodel',
            name='order',
            field=models.CharField(max_length=2000, null=True),
        ),
    ]
