# Generated by Django 4.2.6 on 2023-12-27 07:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_eventmodel_time'),
        ('subcribe2', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcribemodel',
            name='event',
        ),
        migrations.AddField(
            model_name='subcribemodel',
            name='event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='home.eventmodel'),
        ),
    ]
