# Generated by Django 4.2.6 on 2023-12-27 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subcribe2', '0002_remove_subcribemodel_event_subcribemodel_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcribemodel',
            name='totalevent',
            field=models.IntegerField(null=True),
        ),
    ]
