# Generated by Django 4.2.6 on 2024-01-07 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subcribe2', '0003_alter_subcribemodel_totalevent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subcribemodel',
            old_name='totalevent',
            new_name='totalpeople',
        ),
    ]
