# Generated by Django 4.2.6 on 2024-01-07 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subcribe2', '0004_rename_totalevent_subcribemodel_totalpeople'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcribemodel',
            name='totalpeople',
        ),
    ]
