# Generated by Django 4.2.6 on 2023-12-19 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EventModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('time', models.DateTimeField()),
                ('address', models.CharField(max_length=1000)),
                ('topic', models.CharField(max_length=50)),
            ],
        ),
    ]
