# Generated by Django 4.2.6 on 2023-12-25 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_eventmodel_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventmodel',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
