# Generated by Django 4.2.6 on 2023-12-26 12:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0003_eventmodel_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventmodel',
            name='leader',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='eventmodel',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
