# Generated by Django 4.2.6 on 2023-12-29 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_eventmodel_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventmodel',
            name='deadline',
            field=models.DateTimeField(null=True),
        ),
    ]
