# Generated by Django 4.2.6 on 2023-12-29 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_eventmodel_deadline'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventmodel',
            name='deadline',
        ),
        migrations.AddField(
            model_name='eventmodel',
            name='deadlinedate',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='eventmodel',
            name='deadlinetime',
            field=models.TimeField(null=True),
        ),
    ]
