# Generated by Django 4.2.6 on 2023-12-30 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_remove_eventmodel_deadline_eventmodel_deadlinedate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventmodel',
            name='is_completed',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
