# Generated by Django 4.2.6 on 2024-01-06 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_eventmodel_is_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventmodel',
            name='totalpeople',
            field=models.IntegerField(null=True),
        ),
    ]
